# -*- coding: utf-8 -*-
#gehoert zum programmAdressbuch.py

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QAction, QApplication, QFileDialog, QMainWindow, QMessageBox, QTextEdit)  #hinzufuegen!--------------------

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 621)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/adressbook-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(230, 30, 541, 521))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 30, 481, 441))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.vornamelineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.vornamelineEdit.setObjectName("vornamelineEdit")
        self.gridLayout.addWidget(self.vornamelineEdit, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.nachnamelineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.nachnamelineEdit.setObjectName("nachnamelineEdit")
        self.gridLayout.addWidget(self.nachnamelineEdit, 1, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.emaillineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.emaillineEdit.setObjectName("emaillineEdit")
        self.gridLayout.addWidget(self.emaillineEdit, 2, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.handylineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.handylineEdit.setObjectName("handylineEdit")
        self.gridLayout.addWidget(self.handylineEdit, 3, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.tellineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.tellineEdit.setObjectName("tellineEdit")
        self.gridLayout.addWidget(self.tellineEdit, 4, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.geburtstagdateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.geburtstagdateEdit.setObjectName("geburtstagdateEdit")
        self.gridLayout.addWidget(self.geburtstagdateEdit, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.adressetextEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.adressetextEdit.setObjectName("adressetextEdit")
        self.gridLayout.addWidget(self.adressetextEdit, 6, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.notizentextEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.notizentextEdit.setObjectName("notizentextEdit")
        self.gridLayout.addWidget(self.notizentextEdit, 7, 1, 1, 2)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(220, 480, 294, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.hinzufuegenAbbrechenpushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.hinzufuegenAbbrechenpushButton.setObjectName("hinzufuegenAbbrechenpushButton")
        self.horizontalLayout_2.addWidget(self.hinzufuegenAbbrechenpushButton)
        self.aenderungenSpeichernpushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.aenderungenSpeichernpushButton.setObjectName("aenderungenSpeichernpushButton")
        self.horizontalLayout_2.addWidget(self.aenderungenSpeichernpushButton)
        self.hinzufuegenpushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.hinzufuegenpushButton.setObjectName("hinzufuegenpushButton")
        self.horizontalLayout_2.addWidget(self.hinzufuegenpushButton)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 30, 171, 25))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.auswahlcomboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.auswahlcomboBox.setObjectName("auswahlcomboBox")
        self.horizontalLayout.addWidget(self.auswahlcomboBox)
        self.anzeigenpushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.anzeigenpushButton.setObjectName("anzeigenpushButton")
        self.horizontalLayout.addWidget(self.anzeigenpushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNeu = QtWidgets.QAction(MainWindow, triggered=self.klickAufNeu) #hinzufuegen!!!!    , triggered=self.klickAufNeu)--------------------
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNeu.setIcon(icon1)
        self.actionNeu.setObjectName("actionNeu")
        self.actionLoeschen = QtWidgets.QAction(MainWindow, triggered=self.klickAufLoeschen) #!---------------
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoeschen.setIcon(icon2)
        self.actionLoeschen.setObjectName("actionLoeschen")
        self.actionHinzufuegen = QtWidgets.QAction(MainWindow, triggered=self.listeSpeichern) #!------------------
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHinzufuegen.setIcon(icon3)
        self.actionHinzufuegen.setObjectName("actionHinzufuegen")
        self.actionLaden = QtWidgets.QAction(MainWindow, triggered=self.listeLaden) #!----------------------------------
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLaden.setIcon(icon4)
        self.actionLaden.setObjectName("actionLaden")
        self.toolBar.addAction(self.actionNeu)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLaden)
        self.toolBar.addAction(self.actionHinzufuegen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLoeschen)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Adressbuch"))
        self.groupBox.setTitle(_translate("MainWindow", "Angaben"))
        self.label.setText(_translate("MainWindow", "Vorname"))
        self.label_2.setText(_translate("MainWindow", "Nachname"))
        self.label_4.setText(_translate("MainWindow", "E-Mail"))
        self.label_6.setText(_translate("MainWindow", "Handynummer"))
        self.label_5.setText(_translate("MainWindow", "Telefonnummer"))
        self.label_8.setText(_translate("MainWindow", "Geburtstag"))
        self.label_3.setText(_translate("MainWindow", "Adresse"))
        self.label_7.setText(_translate("MainWindow", "Notizen"))
        self.hinzufuegenAbbrechenpushButton.setText(_translate("MainWindow", "Abbrechen"))
        self.aenderungenSpeichernpushButton.setText(_translate("MainWindow", "Änderungen übernehmen"))
        self.hinzufuegenpushButton.setText(_translate("MainWindow", "Hinzufügen"))
        self.anzeigenpushButton.setText(_translate("MainWindow", "Anzeigen"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNeu.setText(_translate("MainWindow", "Neuer Eintrag"))
        self.actionLoeschen.setText(_translate("MainWindow", "Loeschen"))
        self.actionHinzufuegen.setText(_translate("MainWindow", "Speichern"))
        self.actionLaden.setText(_translate("MainWindow", "Laden"))

